package _func

import "github.com/DenisKDO/TSIS1/pkg/structs"

// making team
func PrepareTeam() []structs.Player {
	var players []structs.Player

	var player structs.Player

	player.UniformNumber = "1"
	player.Country = "Japan"
	player.Position = "OP"
	player.FirstName = "Yuji"
	player.SecondName = "Nishida"
	player.Height = "186cm"
	player.Weight = "80kg"
	player.Spike = "350cm"
	player.Block = "335cm"
	player.CurrentClub = "Panasonic Panthers (Japan)"
	players = append(players, player)

	player.UniformNumber = "12"
	player.Country = "Japan"
	player.Position = "OH"
	player.FirstName = "Ran"
	player.SecondName = "Takahashi"
	player.Height = "188cm"
	player.Weight = "72kg"
	player.Spike = "343cm"
	player.Block = "315cm"
	player.CurrentClub = "Vero Volley Monza (Italy)"
	players = append(players, player)

	player.UniformNumber = "14"
	player.Country = "Japan"
	player.Position = "OH"
	player.FirstName = "Yuki"
	player.SecondName = "Ishikawa"
	player.Height = "191cm"
	player.Weight = "84kg"
	player.Spike = "351cm"
	player.Block = "327cm"
	player.CurrentClub = "Allianz Milano (Italy)"
	players = append(players, player)

	player.UniformNumber = "4"
	player.Country = "Japan"
	player.Position = "OP"
	player.FirstName = "Kento"
	player.SecondName = "Miyaura"
	player.Height = "189cm"
	player.Weight = "78kg"
	player.Spike = "347cm"
	player.Block = "320cm"
	player.CurrentClub = "Paris Volley (France)"
	players = append(players, player)

	player.UniformNumber = "5"
	player.Country = "Japan"
	player.Position = "OH"
	player.FirstName = "Tatsunori"
	player.SecondName = "Otsuka"
	player.Height = "194cm"
	player.Weight = "80kg"
	player.Spike = "340cm"
	player.Block = "325cm"
	player.CurrentClub = "Panasonic Panthers (Japan)"
	players = append(players, player)

	player.UniformNumber = "11"
	player.Country = "Japan"
	player.Position = "OH"
	player.FirstName = "Shoma"
	player.SecondName = "Tomita"
	player.Height = "190cm"
	player.Weight = "75kg"
	player.Spike = "342cm"
	player.Block = "320cm"
	player.CurrentClub = "Toray Arrows (Japan)"
	players = append(players, player)

	player.UniformNumber = "30"
	player.Country = "Japan"
	player.Position = "OH"
	player.FirstName = "Masato"
	player.SecondName = "Kai"
	player.Height = "184cm"
	player.Weight = "72kg"
	player.Spike = "352cm"
	player.Block = "330cm"
	player.CurrentClub = "Paris Volley (France)"
	players = append(players, player)

	player.UniformNumber = "2"
	player.Country = "Japan"
	player.Position = "MB"
	player.FirstName = "Onodera"
	player.SecondName = "Taishi"
	player.Height = "201cm"
	player.Weight = "98kg"
	player.Spike = "343cm"
	player.Block = "330cm"
	player.CurrentClub = "Suntory Sunbirds (Japan)"
	players = append(players, player)

	player.UniformNumber = "6"
	player.Country = "Japan"
	player.Position = "MB"
	player.FirstName = "Akihiro"
	player.SecondName = "Yamauchi"
	player.Height = "204cm"
	player.Weight = "80kg"
	player.Spike = "354cm"
	player.Block = "335cm"
	player.CurrentClub = "Panasonic Panthers (Japan)"
	players = append(players, player)

	player.UniformNumber = "10"
	player.Country = "Japan"
	player.Position = "MB"
	player.FirstName = "Kentaro"
	player.SecondName = "Takahashi"
	player.Height = "201cm"
	player.Weight = "103kg"
	player.Spike = "361cm"
	player.Block = "350cm"
	player.CurrentClub = "Toray Arrows (Japan)"
	players = append(players, player)

	player.UniformNumber = "12"
	player.Country = "Japan"
	player.Position = "S"
	player.FirstName = "Masahiro"
	player.SecondName = "Sekita"
	player.Height = "175cm"
	player.Weight = "72kg"
	player.Spike = "324cm"
	player.Block = "305cm"
	player.CurrentClub = "JTEKT Stings (Japan)"
	players = append(players, player)

	player.UniformNumber = "29"
	player.Country = "Japan"
	player.Position = "S"
	player.FirstName = "Ryu"
	player.SecondName = "Yamamoto"
	player.Height = "180cm"
	player.Weight = "65kg"
	player.Spike = "330cm"
	player.Block = "315cm"
	player.CurrentClub = "CS Dinamo București (Romania)"
	players = append(players, player)

	player.UniformNumber = "13"
	player.Country = "Japan"
	player.Position = "L"
	player.FirstName = "Tomohiro"
	player.SecondName = "Ogawa"
	player.Height = "176cm"
	player.Weight = "66kg"
	player.Spike = "312cm"
	player.Block = "290cm"
	player.CurrentClub = "Wolfdogs Nagoya (Japan)"
	players = append(players, player)

	player.UniformNumber = "20"
	player.Country = "Japan"
	player.Position = "L"
	player.FirstName = "Tomohiro"
	player.SecondName = "Yamamoto"
	player.Height = "171cm"
	player.Weight = "69kg"
	player.Spike = "301cm"
	player.Block = "299cm"
	player.CurrentClub = "Panasonic Panthers (Japan)"
	players = append(players, player)

	player.UniformNumber = "1"
	player.Country = "Russia"
	player.Position = "OH"
	player.FirstName = "Yaroslav"
	player.SecondName = "Podlesnykh"
	player.Height = "198cm"
	player.Weight = "89kg"
	player.Spike = "341cm"
	player.Block = "330cm"
	player.CurrentClub = "Dinamo Moscow (Russia)"
	players = append(players, player)

	player.UniformNumber = "4"
	player.Country = "Russia"
	player.Position = "MB"
	player.FirstName = "Artem"
	player.SecondName = "Volvich"
	player.Height = "212cm"
	player.Weight = "96kg"
	player.Spike = "350cm"
	player.Block = "330cm"
	player.CurrentClub = "Zenit Kazan (Russia)"
	players = append(players, player)

	player.UniformNumber = "7"
	player.Country = "Russia"
	player.Position = "OH"
	player.FirstName = "Dmitry"
	player.SecondName = "Volkov"
	player.Height = "201cm"
	player.Weight = "88kg"
	player.Spike = "340cm"
	player.Block = "330cm"
	player.CurrentClub = "Fakel Novy Urengoy (Russia)"
	players = append(players, player)

	player.UniformNumber = "9"
	player.Country = "Russia"
	player.Position = "MB"
	player.FirstName = "Ivan"
	player.SecondName = "Iakovlev"
	player.Height = "207cm"
	player.Weight = "89kg"
	player.Spike = "360cm"
	player.Block = "350cm"
	player.CurrentClub = "Zenit Saint Petersburg (Russia)"
	players = append(players, player)

	player.UniformNumber = "10"
	player.Country = "Russia"
	player.Position = "OH"
	player.FirstName = "Denis"
	player.SecondName = "Bogdan"
	player.Height = "200cm"
	player.Weight = "92kg"
	player.Spike = "350cm"
	player.Block = "340cm"
	player.CurrentClub = "Fakel Novy Urengoy (Russia)"
	players = append(players, player)

	player.UniformNumber = "11"
	player.Country = "Russia"
	player.Position = "S"
	player.FirstName = "Pavel"
	player.SecondName = "Pankov"
	player.Height = "198cm"
	player.Weight = "90kg"
	player.Spike = "345cm"
	player.Block = "330cm"
	player.CurrentClub = "Dinamo Moscow (Russia)"
	players = append(players, player)

	player.UniformNumber = "15"
	player.Country = "Russia"
	player.Position = "OP"
	player.FirstName = "Viktor"
	player.SecondName = "Poletaev"
	player.Height = "196cm"
	player.Weight = "85kg"
	player.Spike = "360cm"
	player.Block = "340cm"
	player.CurrentClub = "Zenit Saint Petersburg (Russia)"
	players = append(players, player)

	player.UniformNumber = "17"
	player.Country = "Russia"
	player.Position = "OP"
	player.FirstName = "Maxim"
	player.SecondName = "Mikhaylov"
	player.Height = "202cm"
	player.Weight = "103kg"
	player.Spike = "360cm"
	player.Block = "340cm"
	player.CurrentClub = "Zenit Kazan (Russia)"
	players = append(players, player)

	player.UniformNumber = "18"
	player.Country = "Russia"
	player.Position = "OH"
	player.FirstName = "Egor"
	player.SecondName = "Kliuka"
	player.Height = "209cm"
	player.Weight = "93kg"
	player.Spike = "370cm"
	player.Block = "350cm"
	player.CurrentClub = "Zenit Saint Petersburg (Russia)"
	players = append(players, player)

	player.UniformNumber = "20"
	player.Country = "Russia"
	player.Position = "MB"
	player.FirstName = "Ilyas"
	player.SecondName = "Kurkaev"
	player.Height = "207cm"
	player.Weight = "95kg"
	player.Spike = "355cm"
	player.Block = "335cm"
	player.CurrentClub = "Lokomotiv Novosibirsk (Russia)"
	players = append(players, player)

	player.UniformNumber = "24"
	player.Country = "Russia"
	player.Position = "S"
	player.FirstName = "Igor"
	player.SecondName = "Kobzar"
	player.Height = "198cm"
	player.Weight = "86kg"
	player.Spike = "337cm"
	player.Block = "315cm"
	player.CurrentClub = "Kuzbass Kemerovo (Russia)"
	players = append(players, player)

	player.UniformNumber = "27"
	player.Country = "Russia"
	player.Position = "L"
	player.FirstName = "Valentin"
	player.SecondName = "Golubev"
	player.Height = "190cm"
	player.Weight = "70kg"
	player.Spike = "310cm"
	player.Block = "305cm"
	player.CurrentClub = "Belogorie (Russia)"
	players = append(players, player)
	return players
}
